/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#141313",
        foreground: "#e5e2e1",
        card: "#201f1f",
        "card-foreground": "#e5e2e1",
        popover: "#201f1f",
        "popover-foreground": "#e5e2e1",
        primary: "#ffffff",
        "primary-foreground": "#2f3131",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        secondary: "#c7c6c6",
        "secondary-foreground": "#2f3131",
        "secondary-container": "#464747",
        "on-secondary-container": "#b5b5b5",
        muted: "#2a2a2a",
        "muted-foreground": "#959595",
        accent: "#353434",
        "accent-foreground": "#ffffff",
        destructive: "#ffb4ab",
        "destructive-foreground": "#690005",
        "destructive-container": "#93000a",
        "on-destructive-container": "#ffdad6",
        border: "#444748",
        input: "#353434",
        ring: "#ffffff",
        brand: {
          DEFAULT: "#ffffff",
          hover: "#e2e2e2",
          surface: "#201f1f",
        },
        surface: {
          DEFAULT: "#141313",
          dim: "#141313",
          bright: "#3a3939",
          "container-lowest": "#0e0e0e",
          "container-low": "#1c1b1b",
          container: "#201f1f",
          "container-high": "#2a2a2a",
          "container-highest": "#353434",
          variant: "#353434",
        },
        outline: "#8e9192",
        "outline-variant": "#444748",
        "sidebar": "#201f1f",
        "sidebar-foreground": "#e5e2e1",
        "sidebar-primary": "#ffffff",
        "sidebar-primary-foreground": "#2f3131",
        "sidebar-accent": "#353434",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#444748",
        "sidebar-ring": "#ffffff",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}
